##
## db config
##

db.jdbcUrl=jdbc:mysql://db:3306/SALESMANAGER?autoReconnect=true&serverTimeZone=UTC&useUnicode=true&characterEncoding=UTF-8
db.user=shopizer
db.password=shopizer_dev_pass
db.driverClass=com.mysql.cj.jdbc.Driver
hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect

db.show.sql=false
db.preferredTestQuery=SELECT 1
db.schema=SALESMANAGER
hibernate.hbm2ddl.auto=update


##
## configuration connection pool
##
db.initialPoolSize=10
db.minPoolSize=20
db.maxPoolSize=70
db.connectionTimeout=10000
db.idleTimeout=600000
db.maxLifetime=1740000
db.validationTimeout=5000
db.leakDetectionThreshold=20000
